# -*- coding: utf-8 -*-
"""UnWordle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q1csBRUBkAs7bIvT0crKcHU0Ozot4LzW
"""

answer_words_file = open("answer_words.txt", "r")
other_words_file = open("other_words.txt", "r")
all_words_file = open("all_words.txt", "r")

answer_words = []
for line in answer_words_file:
  answer_words.append(line.strip())

other_words = []
for line in other_words_file:
  other_words.append(line.strip())

all_words = []
for line in all_words_file:
  all_words.append(line.strip())

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

letter_count = [[0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0], [0, 0 , 0, 0, 0]]

for i in range(5):
  for j in range(len(letters)):
    for k in range(len(answer_words)):
      if answer_words[k][i] == letters[j]:
        letter_count[j][i] += 1

word_scores = []
for word in range(len(answer_words)):
  word_score = 0
  for letter in range(5):
    index = letters.index(answer_words[word][letter])
    word_score += letter_count[index][letter]
  word_scores.append(word_score)

sorted_scores = sorted(word_scores)
sorted_scores.reverse()

sorted_words = []
for num in sorted_scores:
  word_index = word_scores.index(num)
  sorted_words.append(answer_words[word_index])

for i in range(5):
  new_sorted_words = []
  print(sorted_words)
  guess = input("What was your guess: ")
  first_letter = input ("What is the first letter (-, &, !) : ")
  second_letter = input ("What is the second letter (-, &, !): ")
  third_letter = input ("What is the third letter (-, &, !): ")
  fourth_letter = input ("What is the fourth letter (-, &, !): ")
  fifth_letter = input ("What is the fifth letter (-, &, !): ")
  letter_presence = [first_letter, second_letter, third_letter, fourth_letter, fifth_letter]
  for symbol in range(len(letter_presence)):
    if letter_presence[symbol] == "-":
      for word in sorted_words:
        if guess[symbol] not in word:
          new_sorted_words.append(word)
      print(new_sorted_words)

    elif letter_presence[symbol] == "&":
      for word in sorted_words:
        if guess[symbol] in word:
          new_sorted_words.append(word)
        if guess[symbol] != word[symbol]:
          new_sorted_words.append(word)
    
      print(sorted_words)

    elif letter_presence[symbol] == "!":
      for word in sorted_words:
        if guess[symbol] == word[symbol]:
          new_sorted_words.append(word)

    sorted_words = new_sorted_words

